name: Nickel Daily Update

on:
  schedule:
    - cron: "0 1 * * *" # 8h sáng giờ VN
  workflow_dispatch: # Để bấm chạy tay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Cập nhật từ v3 lên v4
        uses: actions/checkout@v4

      - name: Set up Python
        # Cập nhật từ v4 lên v5
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager beautifulsoup4 gspread oauth2client

      - name: Run Python script
        env:
          G_SHEET_CONFIG: ${{ secrets.G_SHEET_CONFIG }}
        # Đảm bảo tên file này khớp với file .py của bạn
        run: python update_nikel.py
