name: Auto Update Nickel Price

on:
  schedule:
    - cron: '0 1 * * *' # Chạy vào 8:00 sáng mỗi ngày (Giờ Việt Nam)
  workflow_dispatch:     # Cho phép bạn bấm nút chạy thử bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        # Đảm bảo file python của bạn tên là update_nikel.py
        run: python update_nikel.py